[package]
name = "libheatmap"
version = "0.1.0"
edition = "2021"
links = "heatmap"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.144"

[build-dependencies]
bindgen = "0.65.1"